sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t keshris/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true keshris/docker-react npm run test
